services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/www/html/vendor
      - .:/app
    working_dir: /app
    command: php -S 0.0.0.0:8000